### ISSUE TITLE
Remove discovery plug-in in favor of hitting Service

### ISSUE THREAD

**Issue by ant31** [pires/docker-elasticsearch-kubernetes#3]
Hi,

I successfully try to remove Elasticsearch discovery plugin Kubernetes

The new configuration is simple:
```yaml
discovery:
  zen.ping.unicast.hosts: ${UNICAST_HOSTS}
```

and in the  ES-RC: 
```yaml
 env:
        - name: UNICAST_HOSTS
          value: 'es-discovery.default.svc.cluster.local'
```

Is this plugin doing something more than discovering new nodes?
